services:
  mongodb:
    image: mongo:7
    container_name: medichat-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_PORT: ${MONGODB_PORT}
    volumes:
      - mongodb_data:/data/db
    networks:
      - medichat-network

  backend:
    image: d3vle0/medichat-backend:latest
    container_name: medichat-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@medichat-mongodb:${MONGODB_PORT}/medichat?authSource=admin
      - HOSPITAL_API_KEY=${HOSPITAL_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - medichat-network

volumes:
  mongodb_data:

networks:
  medichat-network:
    driver: bridge
